### ISSUE TITLE
Missing the example code.

### ISSUE THREAD

**Issue by jazz-mobility** [haifengkao/WZProtocolInterceptor#1]
Hi can you please add how to use this interceptor for scrollview ?

**Comment by haifengkao** [comment]
You can find an example in [HFTableCollectionBindingHelper](https://github.com/haifengkao/HFTableCollectionBindingHelper/blob/6fa914ff0a22a9344c6c192ad94427bd9765c7cd/Pod/Classes/HFCollectionViewBindingHelper.m)
I use it as a proxy of UICollectionViewDelegate. UIScrollView should work in the same way.
